services:
  dotnet-api:
    image: crypto-dotnet
    build:
      context: .
      dockerfile: crypto-dotnet/Dockerfile
    ports:
      - "8980:8080"

  rust-api:
    build:
      context: ./crypto-rust
      dockerfile: Dockerfile.vendor
    ports:
      - "8880:8080"
    environment:
      - CRYPTO_SERVER_IP=0.0.0.0

  client:
    build:
      context: ./crypto-front
      dockerfile: Dockerfile
    ports:
      - "8780:8080"

  proxy:
    image: nginx:stable-alpine
    ports:
      - "8180:80"
    volumes:
      - ./.proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dotnet-api
      - rust-api
      - client
